<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateParentPaymentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('km8_parent_payments', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('organization_id')->index();
            $table->unsignedBigInteger('branch_id')->index();
            $table->unsignedBigInteger('user_id')->index();
            $table->unsignedBigInteger('payment_method_id')->nullable()->default(null);
            $table->unsignedBigInteger('payment_schedule_id')->nullable()->default(null); // Applicable for scheduled payments

            $table->string('payment_ref')->nullable()->default(null); // Generated by kinderm8
            $table->string('transaction_ref')->nullable()->default(null); // Generated by payment gateway
            $table->double('amount', 15, 2);
            $table->date('date');
            $table->enum('payment_execution_type', array(
                'auto',
                'manual'
            ));
            $table->enum('payment_generation_type', array(
                'auto',
                'manual'
            ));

            // Applicable for manual payments only
            $table->enum('manual_payment_type', array(
                'bpay',
                'cash',
                'cheque',
                'direct_debit',
                'direct_deposit',
                'configured_payment',
                'fpos'
            ))->nullable()->default(null);

            $table->date('settlement_date')->nullable()->default(null);

            $table->string('comments')->nullable()->default(null);
            $table->string('fail_reason')->nullable()->default(null);
            $table->json('properties')->nullable()->default(null);

            $table->enum('status', array(
                'approved',
                'pending',
                'submitted',
                'completed',
                'rejected_gateway',
                'rejected_user',
                'refund_success',
                'refund_failed',
                'inactive'
            ));

            $table->softDeletes();
            $table->timestamps();

            $table->foreign('organization_id')
                ->references('id')
                ->on('km8_organization');

            $table->foreign('branch_id')
                ->references('id')
                ->on('km8_organization_branch');

            $table->foreign('user_id')
                ->references('id')
                ->on('km8_users');

            $table->foreign('payment_method_id')
                ->references('id')
                ->on('km8_parent_payment_methods');

            $table->foreign('payment_schedule_id')
                ->references('id')
                ->on('km8_parent_payment_schedules');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('km8_parent_payments');
    }
}
