<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateParentPaymentRefundsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('km8_parent_payment_refunds', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('organization_id')->index();
            $table->unsignedBigInteger('branch_id')->index();
            $table->unsignedBigInteger('user_id')->index();
            $table->unsignedBigInteger('payment_id')->index();

            $table->string('refund_ref')->nullable()->default(null); // Generated by kinderm8
            $table->string('transaction_ref')->nullable()->default(null); // Generated by payment gateway
            $table->double('amount', 15, 2);
            $table->date('date');
            $table->string('comments')->nullable()->default(null);
            $table->enum('status', array(
                'approved',
                'pending',
                'submitted',
                'completed',
                'rejected_gateway',
                'rejected_user',
            ));
            $table->json('properties')->nullable()->default(null);

            $table->softDeletes();
            $table->timestamps();

            $table->foreign('organization_id')
                ->references('id')
                ->on('km8_organization');

            $table->foreign('branch_id')
                ->references('id')
                ->on('km8_organization_branch');

            $table->foreign('user_id')
                ->references('id')
                ->on('km8_users');

            $table->foreign('payment_id')
                ->references('id')
                ->on('km8_parent_payments');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('km8_parent_payment_refunds');
    }
}